version: "3"

services:
  postgres:
    image: postgres
    container_name: jwt-security
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=jwt-security
      - TZ=GMT
    volumes:
      - "./data/jwt-security/postgres:/var/lib/postgres/data"
    ports:
      - 5432:5432