CREATE SEQUENCE topic_id_sequence INCREMENT BY 50;
CREATE SEQUENCE course_id_sequence INCREMENT BY 50;
CREATE SEQUENCE answer_id_sequence INCREMENT BY 50;
CREATE SEQUENCE role_id_sequence INCREMENT BY 50;
CREATE SEQUENCE user_id_sequence INCREMENT BY 50;
CREATE SEQUENCE author_id_sequence INCREMENT BY 50;