--- ALTER TABLES TOPIC REMOVE AND ADD FIELDS CREATE AND UPDATE DATA
ALTER TABLE topic DROP COLUMN createAt;
ALTER TABLE topic DROP COLUMN updatedAt;

ALTER TABLE topic ADD createdAt TIMESTAMP;
ALTER TABLE topic ADD updatedAt TIMESTAMP;

-- ADD COLUMN CREATE AND UPDATE DATA ON TABLE AUTHOR
ALTER TABLE author ADD createdAt TIMESTAMP;
ALTER TABLE author ADD updatedAt TIMESTAMP;

-- ADD COLUMN CREATE AND UPDATE DATA ON TABLE COURSE
ALTER TABLE course ADD createdAt TIMESTAMP;
ALTER TABLE course ADD updatedAt TIMESTAMP;

--- ALTER TABLES TOPIC REMOVE AND ADD FIELDS CREATE AND UPDATE DATA
ALTER TABLE answer DROP COLUMN createAt;

ALTER TABLE answer ADD createdAt TIMESTAMP;
ALTER TABLE answer ADD updatedAt TIMESTAMP;

