--- ALTER TABLES TOPIC REMOVE AND ADD FIELDS CREATE AND UPDATE DATA
ALTER TABLE topic DROP COLUMN createdAt;
ALTER TABLE topic DROP COLUMN updatedAt;

ALTER TABLE topic ADD created_at TIMESTAMP;
ALTER TABLE topic ADD updated_at TIMESTAMP;

-- ADD COLUMN CREATE AND UPDATE DATA ON TABLE AUTHOR
ALTER TABLE author DROP COLUMN createdAt;
ALTER TABLE author DROP COLUMN updatedAt;

ALTER TABLE author ADD created_at TIMESTAMP;
ALTER TABLE author ADD updated_at TIMESTAMP;

-- ADD COLUMN CREATE AND UPDATE DATA ON TABLE COURSE
ALTER TABLE course DROP COLUMN createdAt;
ALTER TABLE course DROP COLUMN updatedAt;

ALTER TABLE course ADD created_at TIMESTAMP;
ALTER TABLE course ADD updated_at TIMESTAMP;

--- ALTER TABLES TOPIC REMOVE AND ADD FIELDS CREATE AND UPDATE DATA
ALTER TABLE answer DROP COLUMN createdAt;
ALTER TABLE answer DROP COLUMN updatedAt;

ALTER TABLE answer ADD created_ad TIMESTAMP;
ALTER TABLE answer ADD updated_at TIMESTAMP;